version: '3'

vars:
env:
  MYENV: 'globalenv'

dotenv: ['.env']

tasks:
  default:
    desc: "Show all tasks"
    cmds:
      - task --list-all
  globalenv:
    desc: "Check global environment access"
    cmds:
      - echo $MYENV
    silent: true
  localenv:
    desc: "Check local environment access"
    cmds:
      - echo $MYENV
    silent: true
    env:
      MYENV: 'localenv'
  dotenv:
    desc: "Check dotenv file access"
    cmds:
      - echo $DOT_ENV
    silent: true
  lint:go:
    desc: "Run linters"
    cmds:
      - ./bin/golangci-lint run ./...
    dir: ./backend
  test:go:
    desc: "Run tests"
    cmds:
      - go test -v ./...
    dir: ./backend
  lint:ts:
    desc: "Run TS linters"
    cmds:
      - pnpm run lint
    dir: ./frontend
  fmt:ts:
    desc: "Format TS code"
    cmds:
      - pnpm run format
    dir: ./frontend
  test:ts:
    desc: "Run TS tests"
    cmds:
      - pnpm run test
    dir: ./frontend
  up:
    desc: "Run TS and Go servers"
    cmds:
      - pnpm run start
    dir: ./frontend
  up:sb:
    desc: "Run TS server with Storybook"
    cmds:
      - pnpm run storybook
    dir: ./frontend
